### ISSUE TITLE
Query: externals assets folder, do you really need them?

### ISSUE THREAD

**Issue by duttonw** [Qld-Health-Online-Team/design-system#160]
Hi,

Just wondering if any of these files are in use. This is in relation to clean up in combination with https://github.com/Qld-Health-Online-Team/design-system/pull/159 and https://github.com/qld-gov-au/qgds-vanilla/pull/20

| file | commit | last updated |
|---|---|---|
|[componentPreview.js](https://github.com/Qld-Health-Online-Team/design-system/blob/master/src/externals/componentPreview.js) |[copied over bulk of core](https://github.com/Qld-Health-Online-Team/design-system/commit/dc7b793a7d366c4a1fa789b89cff9523809a510d) |2 years ago|
|[dsComponentLoader.js](https://github.com/Qld-Health-Online-Team/design-system/blob/master/src/externals/dsComponentLoader.js) |[copied over bulk of core](https://github.com/Qld-Health-Online-Team/design-system/commit/dc7b793a7d366c4a1fa789b89cff9523809a510d) |2 years ago|
|[esri-leaflet-vector.js](https://github.com/Qld-Health-Online-Team/design-system/blob/master/src/externals/esri-leaflet-vector.js) |[copied over bulk of core](https://github.com/Qld-Health-Online-Team/design-system/commit/dc7b793a7d366c4a1fa789b89cff9523809a510d) |2 years ago|
|[esri-leaflet.js](https://github.com/Qld-Health-Online-Team/design-system/blob/master/src/externals/esri-leaflet.js)| [copied over bulk of core](https://github.com/Qld-Health-Online-Team/design-system/commit/dc7b793a7d366c4a1fa789b89cff9523809a510d)| 2 years ago|
|[fb-handlebars.min.js](https://github.com/Qld-Health-Online-Team/design-system/blob/master/src/externals/fb-handlebars.min.js)| [copied over bulk of core](https://github.com/Qld-Health-Online-Team/design-system/commit/dc7b793a7d366c4a1fa789b89cff9523809a510d)| 2 years ago|
|[fb-typeahead.bundle.min.js](https://github.com/Qld-Health-Online-Team/design-system/blob/master/src/externals/fb-typeahead.bundle.min.js) |[copied over bulk of core](https://github.com/Qld-Health-Online-Team/design-system/commit/dc7b793a7d366c4a1fa789b89cff9523809a510d) |2 years ago|
|[funnelback.autocompletion-2.6.0.js](https://github.com/Qld-Health-Online-Team/design-system/blob/master/src/externals/funnelback.autocompletion-2.6.0.js)|[copied over bulk of core](https://github.com/Qld-Health-Online-Team/design-system/commit/dc7b793a7d366c4a1fa789b89cff9523809a510d) |2 years ago|
|[getPagination.js](https://github.com/Qld-Health-Online-Team/design-system/blob/master/src/externals/getPagination.js) |[copied over bulk of core](https://github.com/Qld-Health-Online-Team/design-system/commit/dc7b793a7d366c4a1fa789b89cff9523809a510d) |2 years ago|
|[handlebars.min-v4.7.8.js](https://github.com/Qld-Health-Online-Team/design-system/blob/master/src/externals/handlebars.min-v4.7.8.js)|[updated handlebars](https://github.com/Qld-Health-Online-Team/design-system/commit/93968dd52c3d703526494663120f71f39f44078b) |10 months ago|
|[leaflet.js](https://github.com/Qld-Health-Online-Team/design-system/blob/master/src/externals/leaflet.js)| [copied over bulk of core](https://github.com/Qld-Health-Online-Team/design-system/commit/dc7b793a7d366c4a1fa789b89cff9523809a510d) |2 years ago|
|[populateDatastoreSim.js](https://github.com/Qld-Health-Online-Team/design-system/blob/master/src/externals/populateDatastoreSim.js)| [copied over bulk of core](https://github.com/Qld-Health-Online-Team/design-system/commit/dc7b793a7d366c4a1fa789b89cff9523809a510d) |2 years ago|
|[tinymce_classes.css](https://github.com/Qld-Health-Online-Team/design-system/blob/master/src/externals/tinymce_classes.css)| [copied over bulk of core](https://github.com/Qld-Health-Online-Team/design-system/commit/dc7b793a7d366c4a1fa789b89cff9523809a510d) |2 years ago|

**Comment by pedroportella** [comment]
All of them are in use for now and needs to be kept.
